name: emotionenv-2
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0=py310hca03da5_0
  - aom=3.6.0=h313beb8_0
  - astunparse=1.6.3=py_0
  - audioread=3.0.1=py310hbe9552e_3
  - blas=1.0=openblas
  - bottleneck=1.4.2=py310hbda83bc_0
  - brotlicffi=1.0.9.2=py310h313beb8_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h191e429_0
  - certifi=2025.10.5=py310hca03da5_0
  - cffi=1.17.1=py310h3eb5a62_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - contourpy=1.3.1=py310h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h80987f9_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - ffmpeg=4.3.2=h38cfed3_3
  - flatbuffers=24.3.25=h313beb8_0
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.60.1=py310h254cc4a_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gast=0.6.0=pyhd3eb1b0_0
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - gmp=6.3.0=h7bae524_2
  - gnutls=3.6.13=h706517b_1
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=hc377ac9_1
  - grpcio=1.71.0=py310h313beb8_0
  - h5py=3.14.0=py310h2232773_0
  - harfbuzz=10.2.0=he637ebf_1
  - hdf5=1.14.5=hd77251f_2
  - icu=73.1=h313beb8_0
  - idna=3.7=py310hca03da5_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jpeg=9f=h2f69dba_0
  - keras=3.11.2=py310h3d9d723_0
  - kiwisolver=1.4.8=py310h313beb8_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libavif=1.1.1=h80987f9_0
  - libcurl=8.15.0=hcdd2897_0
  - libcxx=20.1.8=h8869778_0
  - libdeflate=1.22=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libflac=1.4.1=h7ea286d_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.2=hdc2269c_0
  - libgrpc=1.71.0=h62f6fdd_0
  - libiconv=1.16=h80987f9_3
  - libnghttp2=1.57.0=h62f6fdd_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=hf2bb037_0
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=5.29.3=h14f15fd_1
  - libre2-11=2024.07.02=h313beb8_0
  - librosa=0.9.2=pyhd8ed1ab_0
  - libsndfile=1.1.0=hb7217d7_0
  - libsqlite=3.50.4=hf8de324_0
  - libssh2=1.11.1=h3e2b118_0
  - libtiff=4.7.0=h91aec0a_0
  - libvorbis=1.3.7=h81086ad_2
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.8=h0b34f26_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - llvmlite=0.44.0=py310h5fad91f_2
  - lz4-c=1.9.4=h313beb8_1
  - markdown=3.8=py310hca03da5_0
  - markdown-it-py=2.2.0=py310hca03da5_1
  - markupsafe=3.0.2=py310h80987f9_0
  - matplotlib-base=3.10.6=py310h066045a_0
  - mdurl=0.1.2=py310hca03da5_0
  - ml_dtypes=0.5.1=py310h6e33161_0
  - mpg123=1.30.2=hb7217d7_1
  - mpi=1.0=mpich
  - mpi4py=4.0.3=py310h062c92d_0
  - mpich=4.1.1=he2630cc_0
  - namex=0.1.0=py310hca03da5_0
  - ncurses=6.5=hee39554_0
  - nettle=3.6=hc6a1b29_0
  - numba=0.61.2=py310hd3faf9e_1
  - numexpr=2.11.0=py310h8c72970_1
  - numpy=2.0.1=py310h3b2db8e_1
  - numpy-base=2.0.1=py310ha9811e2_1
  - openh264=2.1.1=h98b2900_0
  - openjpeg=2.5.2=hba36e21_1
  - openssl=3.5.4=h5503f6c_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optree=0.14.1=py310h48ca7d4_0
  - packaging=25.0=py310hca03da5_0
  - pandas=2.3.3=py310hc6ded6b_0
  - pcre2=10.42=hb066dcc_1
  - pillow=11.3.0=py310h6dd570d_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - pooch=1.8.2=pyhd8ed1ab_3
  - protobuf=5.29.3=py310h514c7bf_0
  - pycparser=2.23=py310hca03da5_0
  - pygments=2.19.1=py310hca03da5_0
  - pyparsing=3.2.0=py310hca03da5_0
  - pysocks=1.7.1=py310hca03da5_0
  - pysoundfile=0.11.0=pyhd8ed1ab_0
  - python=3.10.15=hdce6c4c_2_cpython
  - python-dateutil=2.9.0post0=py310hca03da5_2
  - python-flatbuffers=24.3.25=py310hca03da5_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=py310hca03da5_0
  - re2=2024.07.02=h48ca7d4_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py310hca03da5_0
  - resampy=0.4.3=pyhd8ed1ab_1
  - rich=13.9.4=py310hca03da5_0
  - scikit-learn=1.7.2=py310h660f142_0
  - scipy=1.15.3=py310h132fc3c_1
  - seaborn=0.13.2=py310hca03da5_3
  - setuptools=78.1.1=py310hca03da5_0
  - six=1.17.0=py310hca03da5_0
  - snappy=1.2.1=h313beb8_0
  - sqlite=3.50.2=h79febb2_1
  - tensorboard=2.18.0=py310hca03da5_0
  - tensorboard-data-server=0.7.0=py310ha6e5c4f_1
  - tensorflow=2.18.1=cpu_py310h18e2dce_0
  - tensorflow-base=2.18.1=cpu_py310h97f355d_0
  - termcolor=2.1.0=py310hca03da5_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hcd8a7d5_0
  - typing-extensions=4.15.0=py310hca03da5_0
  - typing_extensions=4.15.0=py310hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py310hca03da5_0
  - werkzeug=3.1.3=py310hca03da5_0
  - wheel=0.45.1=py310hca03da5_0
  - wrapt=1.17.0=py310h80987f9_0
  - x264=1!161.3030=h3422bc3_1
  - xz=5.6.4=h80987f9_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - filelock==3.20.0
      - fsspec==2025.9.0
      - jinja2==3.1.6
      - mpmath==1.3.0
      - networkx==3.4.2
      - sympy==1.14.0
      - torch==2.8.0
      - torchvision==0.23.0
prefix: /opt/anaconda3/envs/emotionenv
